baseURL = "https://epic-hoover-72e16c.netlify.app/"
languageCode = "en-us"
title = "JAMSite"
theme = "tale"
copyright = "Copyright 2019 Stackacademy.tv"
disableKinds = ["section"]

[outputs]
  home = ["HTML", "JSON"]
